/*
 * Do not edit this file.
 *
 * This file ensures that your package will export a
 * 'run_testthat_tests' routine that can be used to run
 * other tests available within your package.
 */
#define TESTTHAT_TEST_RUNNER
#include <tests/testthat.h>
